INSERT INTO Article_21
	VALUES ('21354', 'WWW.DHJGF.COM', '1.50');
	
INSERT INTO CATEGORY
	VALUES ('RLHEGFOLWURHGFO;URWHGO;RUWHG', '01-02-1998');	
	
INSERT INTO USER
	VALUES ('21-03-1258', '536.12', 'KDUFGHOEURGHOLERUGHOUNJOWLUIENOIFE OUWEHRFOWJUHERTFPW');
	
INSERT INTO TAG
	VALUES ('LUKE SKYWALKER', 'RFGHRTGHRTH');	
