--------------------------------------------------------
--  File created - Понеделник-Април-14-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ARTICLE
--------------------------------------------------------

  CREATE TABLE "ELSYS"."ARTICLE" 
   (	"ID" NUMBER, 
	"CONTENT" VARCHAR2(20 BYTE), 
	"URL" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORY_PART1
--------------------------------------------------------

  CREATE TABLE "ELSYS"."CATEGORY_PART1" 
   (	"DESCRIPTION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORY_PART2
--------------------------------------------------------

  CREATE TABLE "ELSYS"."CATEGORY_PART2" 
   (	"ID" NUMBER, 
	"DATE_CREATED" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TAG
--------------------------------------------------------

  CREATE TABLE "ELSYS"."TAG" 
   (	"ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"USER_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "ELSYS"."USERS" 
   (	"PASSWORD" VARCHAR2(20 BYTE), 
	"AGE" NUMBER(*,0), 
	"ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"CATEGORY_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ELSYS.ARTICLE
SET DEFINE OFF;
Insert into ELSYS.ARTICLE (ID,CONTENT,URL,NAME) values (1,'ghg','dfh','fcgh');
Insert into ELSYS.ARTICLE (ID,CONTENT,URL,NAME) values (2,'fh','ffh','n');
REM INSERTING into ELSYS.CATEGORY_PART1
SET DEFINE OFF;
Insert into ELSYS.CATEGORY_PART1 (DESCRIPTION) values ('df');
Insert into ELSYS.CATEGORY_PART1 (DESCRIPTION) values ('fdg');
REM INSERTING into ELSYS.CATEGORY_PART2
SET DEFINE OFF;
Insert into ELSYS.CATEGORY_PART2 (ID,DATE_CREATED) values (1,to_date('2013-02-01','RRRR-MM-DD'));
Insert into ELSYS.CATEGORY_PART2 (ID,DATE_CREATED) values (2,to_date('2011-02-02','RRRR-MM-DD'));
REM INSERTING into ELSYS.TAG
SET DEFINE OFF;
Insert into ELSYS.TAG (ID,DESCRIPTION,NAME,USER_ID) values (1,'vv','fg',null);
Insert into ELSYS.TAG (ID,DESCRIPTION,NAME,USER_ID) values (2,'vg','h',null);
REM INSERTING into ELSYS.USERS
SET DEFINE OFF;
Insert into ELSYS.USERS (PASSWORD,AGE,ID,DESCRIPTION,CATEGORY_ID) values ('dsf',1,1,'df',1);
Insert into ELSYS.USERS (PASSWORD,AGE,ID,DESCRIPTION,CATEGORY_ID) values ('f',2,2,'f',2);
