CREATE TABLE Users (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, Name VARCHAR (30), Email TEXT, Age INT);
CREATE TABLE Groups (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, Name VARCHAR (30), Date_founded_on DATE);
CREATE TABLE Events (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, Name VARCHAR (30), Date DATE, Location VARCHAR (100));
CREATE TABLE user_groups(id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, groups_id INT NOT NULL);
CREATE TABLE events_groups (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, events_id INT NOT NULL, groups_id INT NOT NULL);
ALTER TABLE user_groups ADD FOREIGN KEY (user_id) REFERENCES Users(id);
ALTER TABLE events_groups ADD FOREIGN KEY (groups_id) REFERENCES Groups(id);
